# Change these first
owner: captv89
repo: uptime-monitor

sites:
    - name: Portfolio
      url: https://captv.ovh/
      expectedStatusCode:
          - 0
          - 200
          - 301
    - name: Photography
      url: https://captv89.github.io/photography/
      expectedStatusCode:
          - 0
          - 200
          - 301
    - name: Searoute
      url: https://searoute.captv.ovh
    - name: CII
      url: https://cii.captv.ovh/
    - name: Svelte GeoMap
      url: https://svelte-map-theta.vercel.app/
    - name: Calculator
      url: https://svelte-calculator-alpha.vercel.app/

status-website:
    baseUrl: /uptime-monitor
    logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
    name: Uptime Monitor
    introTitle: 'Check the uptime of my websites, powered entirely by GitHub.'
    navbar:
        - title: Status
          href: /
        - title: GitHub
          href: https://github.com/captv89/uptime-monitor
    theme: dark
