# Change these first
owner: captv89
repo: uptime-monitor

sites:
    - name: Portfolio
      url: https://captv.ovh
    - name: Photography
      url: https://captv.ovh/photography/
    - name: Searoute
      url: https://searoute.captv.ovh
    - name: CII
      url: https://cii.captv.ovh/
    - name: Svelte GeoMap
      url: https://svelte-map-theta.vercel.app/
    - name: Calculator
      url: https://svelte-calculator-alpha.vercel.app/

status-website:
    cname: captv.ovh
    logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
    name: Portfolio
    introTitle: 'My portfolio page, powered entirely by GitHub.'
    navbar:
        - title: Status
          href: /
        - title: GitHub
          href: https://github.com/captv89/uptime-monitor
